dist: xenial
sudo: true

before_install:
  - python3 setup.py install
  - sudo apt-get -y update

install:
  - pip install pytest-cov
  - pip install .

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

script:
  - python3 -m pytest
  - ./test.sh
